# グループごとの名前色設定
# カラーコード一覧:
# &0 黒, &1 濃い青, &2 緑, &3 青緑, &4 赤, &5 紫, &6 金, &7 薄灰
# &8 灰, &9 明るい青, &a 明るい緑, &b 明るい青緑, &c ピンク, &d 明るい紫, &e 黄色, &f 白

groups:
  default: '&7'
  admin: '&c'
  vip: '&b'
